# site settings

title: Sandipan Seal
description: An experienced developer and CS Master student
taglong:  An experienced developer and CS Master student
tagshort: Jekyll theme
url: https://cvless.netlify.app
baseurl: ""
permalink: pretty
repo: 

# author settings

author:
  name: Sandipan Seal
  email: sandipanseal68@gmail.com
photo:/demo/assets/profile.PNG

# social media links

social:
  facebook: username
  github: username
  linkedin: Sandipan Seal

# build settings

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
